# Generated by Django 3.2.9 on 2022-01-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('matriculeEns', models.IntegerField(primary_key=True, serialize=False)),
                ('nomEnseignant', models.CharField(max_length=40)),
                ('prenomEnseignant', models.CharField(max_length=30)),
                ('grade', models.CharField(choices=[('ma_b', 'maître assistant B'), ('ma_a', 'maître assistant A'), ('mc_b', 'maître conférence B'), ('mc_a', 'maître conférence A'), ('phd', 'proffesseur')], max_length=16)),
                ('département', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEntreprise', models.CharField(max_length=40)),
                ('secteur', models.CharField(max_length=40)),
                ('addresseEntreprise', models.CharField(max_length=80)),
                ('emailEntreprise', models.EmailField(max_length=254, null=True)),
                ('telEntreprise', models.PositiveBigIntegerField(null=True)),
                ('siteweb', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('matricule', models.IntegerField(primary_key=True, serialize=False)),
                ('nomEtudiant', models.CharField(max_length=40)),
                ('prenomEtudiant', models.CharField(max_length=30)),
                ('dateNaiss', models.DateField()),
                ('anneeEtudes', models.CharField(choices=[('1', '1CP'), ('2', '2CP'), ('3', '1CS'), ('4', '2CS'), ('5', '3CS')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TypeStages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('désignation', models.CharField(choices=[(1, 'stage ouvrier'), (2, 'stage téchnique'), (3, 'stage fin de cursus')], max_length=16)),
                ('obligatoire', models.BooleanField()),
                ('nbrePageRapport', models.IntegerField()),
                ('duréeEstimée', models.IntegerField()),
                ('debutPeriode', models.DateField()),
                ('finPeriode', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomProjet', models.CharField(max_length=60)),
                ('objectifStage', models.TextField(max_length=100)),
                ('annee', models.IntegerField()),
                ('dateDeb', models.DateField()),
                ('dateFin', models.DateField(null=True)),
                ('dureeReel', models.IntegerField()),
                ('nbreEtudiant', models.IntegerField(default=1)),
                ('numEntreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.entreprise')),
                ('numType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.typestages')),
            ],
        ),
        migrations.CreateModel(
            name='Encadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEncadreur', models.CharField(max_length=40)),
                ('prenomEncadreur', models.CharField(max_length=30)),
                ('poste', models.CharField(max_length=30, null=True)),
                ('numEntreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Faire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appréciation', models.IntegerField(max_length=2)),
                ('matriculeEtu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.etudiant')),
                ('numStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stage')),
            ],
            options={
                'unique_together': {('numStage', 'matriculeEtu')},
            },
        ),
        migrations.CreateModel(
            name='Evaluer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteEvaluation', models.IntegerField(max_length=2, null=True)),
                ('remarque', models.TextField(null=True)),
                ('numEnc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.encadreur')),
                ('numStage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.stage')),
            ],
            options={
                'unique_together': {('numStage', 'numEnc')},
            },
        ),
    ]
