# Generated by Django 3.2.9 on 2022-01-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='matriculeEns',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
