# Generated by Django 3.2.9 on 2022-01-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220119_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='anneeEtudes',
            field=models.CharField(choices=[('1CP', '1CP'), ('2CP', '2CP'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=3),
        ),
    ]
