# Generated by Django 3.2.9 on 2022-01-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_etudiant_anneeetudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('maître assistant B', 'ma_b'), ('maître assistant A', 'ma_a'), ('maître conférence B', 'mc_b'), ('maître conférence A', 'mc_a'), ('proffesseur', 'phd')], max_length=30),
        ),
    ]
