# Generated by Django 3.2.9 on 2022-01-19 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_enseignant_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='addresseEntreprise',
            new_name='adresseEntreprise',
        ),
        migrations.AddField(
            model_name='stage',
            name='numEncadreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.encadreur'),
        ),
        migrations.AddField(
            model_name='stage',
            name='numEnseignant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.enseignant'),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('ma_b', 'maître assistant B'), ('ma_a', 'maître assistant A'), ('mc_b', 'maître conférence B'), ('mc_a', 'maître conférence A'), ('phd', 'proffesseur')], max_length=16),
        ),
    ]
