# Generated by Django 3.2.9 on 2022-01-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220119_1133'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faire',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='faire',
            name='matriculeEtu',
        ),
        migrations.RemoveField(
            model_name='faire',
            name='numStage',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='dateFin',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='nbreEtudiant',
        ),
        migrations.AddField(
            model_name='stage',
            name='etudiants',
            field=models.ManyToManyField(related_name='stages', to='backend.Etudiant'),
        ),
        migrations.AddField(
            model_name='stage',
            name='noteEvaluation',
            field=models.IntegerField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='remarqueEncadreur',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Evaluer',
        ),
        migrations.DeleteModel(
            name='Faire',
        ),
    ]
