# Generated by Django 3.2.9 on 2022-01-19 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220119_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='numEncadreur',
            new_name='Encadreur',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='numEnseignant',
            new_name='Enseignant',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='numEntreprise',
            new_name='Entreprise',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='numType',
            new_name='Type',
        ),
    ]
