# Generated by Django 3.2.9 on 2022-01-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220119_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestages',
            name='désignation',
            field=models.CharField(max_length=30),
        ),
    ]
