# Generated by Django 3.2.9 on 2022-01-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_typestages_désignation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typestages',
            name='debutPeriode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='typestages',
            name='finPeriode',
            field=models.CharField(max_length=20),
        ),
    ]
