# Generated by Django 3.2.9 on 2022-01-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220119_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='Encadreur',
            new_name='encadreur',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='Enseignant',
            new_name='enseignant',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='Entreprise',
            new_name='entreprise',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='Type',
            new_name='type',
        ),
    ]
