# Generated by Django 3.2.9 on 2022-01-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20220119_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='remarqueEncadreur',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('maître assistant B', 'ma_b'), ('maître assistant A', 'ma_a'), ('maître conférence B', 'mc_b'), ('maître conférence A', 'mc-a'), ('proffesseur', 'phd')], max_length=22),
        ),
    ]
