# Generated by Django 3.2.9 on 2022-01-20 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220120_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encadreur',
            old_name='numEntreprise',
            new_name='entreprise',
        ),
    ]
