# Generated by Django 3.2.9 on 2022-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_rename_numentreprise_encadreur_entreprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(choices=[('maître assistant B', 'maître assistant B'), ('maître assistant A', 'maître assistant A'), ('maître conférence B', 'maître conférence B'), ('maître conférence A', 'maître conférence A'), ('proffesseur', 'proffesseur')], max_length=22),
        ),
    ]
