# Generated by Django 3.2.9 on 2022-01-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_enseignant_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='noteEvaluation',
            field=models.IntegerField(null=True),
        ),
    ]
